spring:
  data:
    mongodb:
      uri: mongodb://oriozadmin:oriozsecret@localhost:27017/orioz-community?authSource=admin
      auto-index-creation: true

server:
  port: 8082

app:
  admin:
    maxMember: 2
